feat : 스테이지 별 배경음악 설정 및 음소거 버튼 기능 구현
145pip/link pull request #16
Opened 2023-03-23 15:33 UTC by yourchaee

## 개요
- `three.js`에 내장된 `Web Audio API`를 통해 배경음악 설정
- 음소거 버튼 클릭 시 배경음악이 중단되는 기능 구현

## 작업 내용

### 배경음악 설정
- 배경음악 설정 기본 세팅
```const listener = new THREE.AudioListener();
  const sound = new THREE.Audio(listener);
  const audioLoader = new THREE.AudioLoader();
```
- 음악 재생이 끝나면 자동으로 재생될 수 있도록 `setLoop()` 메서드를 이용했습니다.
- 초기 재생시 음량은 `setVolume()` 메서드를 이용했습니다.
- 초기에 자동 재생은 `play()` 메서드를 이용했습니다.

### 음소거 버튼 기능
- 버튼 클릭 시 토글 핸들러를 작동시켜 음소거 또는 음악을 재생하는 기능입니다.
- 음소거시 `sound.pause()` 메서드를 이용했습니다.

### 백그라운드 세팅 컴포넌트 재구성
- 음소거 버튼은 게임메뉴 컴포넌트에 있었는데, 불필요한 `props-drilling`이 발생하게 되어 백그라운드 세팅 컴포넌트를 만들고 버튼 위치를 이동시켰습니다.

## 특이 사항
N/A

2023-03-23 16:20 UTC, j25nkh commented on src/components/menus/GameMenu.js
> +        <Modal handleModalClose={handleModalClose} message={message} />
각 버튼의 핸들러 이름이 handle ~ Button Click 인 것처럼, handleModalClick의 네이밍이 어떨까요?
```suggestion
        <Modal handleModalClick={handleModalClose} message={message} />
```

2023-03-23 16:22 UTC, j25nkh commented on src/components/menus/GameMenu.js
> -      <SoundControlButton />
Sound Control 버튼은 더이상 존재하지 않는 건가요?

2023-03-23 16:24 UTC, j25nkh commented on src/components/modals/Modal.js
> +          handleModalClose={handleModalClose}
같은 핸들러가 연달아 연결 되었는데 개선이 필요해 보입니다.

2023-03-23 16:28 UTC, j25nkh commented on src/components/music/BackgroundMusicSetting.js
> +import { useEffect, useState } from "react";
`react`관련 import가 `three`관련 import보다 상단에 위치하면 맥락과 같은 흐름일 것 같아요 :)

2023-03-23 16:29 UTC, j25nkh commented on src/components/music/BackgroundMusicSetting.js
> +export default function BackgroundMusicSetting() {
- 각 stage별로 배경음악이 다를 경우 music folder 안에 각각의 파일이 생성될 것 같습니다. 확장성을 고려하여 StageZeroBackgroundMusic 정도의 파일명과 함수명이 어떨까요?
- Setting은 이름에서 빼주시는게 좋을 것 같아요 :)

2023-03-23 16:31 UTC, j25nkh commented on src/components/music/BackgroundMusicSetting.js
> +  const [isMusicPlaying, setIsMusicPlaying] = useState(true);
boolean 값의 상태를 설정해주셨네요! 현재 그대로 사용하셔도 무방한 이름이라 생각합니다.
다만 더 짧으면서 직관적인 isMusicOn이 어떨까요?

2023-03-23 16:38 UTC, j25nkh requested changes
오늘도 고생많으셨습니다 윤채님.
처음 구현하시는 기능이실 텐데 문제없이 잘 작동해서 뿌듯하네요 👍 
최대한 꼼꼼히 리뷰 남겨보았습니다.

2023-03-23 16:41 UTC, xollee reviewed
고생하셨습니다!
근데 음악을 껐을 때 원래 버튼 모양이 바뀌어야 하지 않나요?
음악을 껐는지 켰는지 구분이 안 돼서 계속 눌러봤습니다 😢

2023-03-23 16:41 UTC, xollee commented on src/components/menus/GameMenu.js
> +        <Modal handleModalClose={handleModalClose} message={message} />
원래 onClose에서 수정한 이유가 있을까요?

2023-03-23 16:41 UTC, xollee commented on src/components/music/BackgroundMusicSetting.js
> +  }, [isMusicPlaying, sound]);
useEffect와 handleToggleSoundButtonClick의 기능이 한 곳에서만 해도 괜찮을 것 같아 보입니다

2023-03-24 02:09 UTC, yourchaee commented on src/components/menus/GameMenu.js
> +        <Modal handleModalClose={handleModalClose} message={message} />
제안 감사합니다. 그런데 모달창을 클릭 했을 때 handleModalClose 함수는 모달창을 닫게 하는 역할이라서 제안은 감사하지만, 변수명은 그대로 두는게 혼란을 줄일 수 있을 것 같습니다 :)

2023-03-24 02:16 UTC, yourchaee commented on src/components/menus/GameMenu.js
> +        <Modal handleModalClose={handleModalClose} message={message} />
네 handleModalClose 함수가 실제로 실행되는 곳은 Modal 컴포넌트 내에 취소 버튼입니다. 그래서 Modal 창 자체에 onClose로 prop명을 주게되면, 실질적으로 작동해야하는 취소 버튼 기능이 작동하지 않아서 네이밍을 수정했습니다.

2023-03-24 02:38 UTC, yourchaee commented on src/components/menus/GameMenu.js
> -      <SoundControlButton />
넵 말씀해주신 부분을 컴포넌트 분리 전에 생각해보았습니다.
컴포넌트의 위치를 동일하게 유지하려면 리덕스를 이용해 음소거 버튼의 상태 관리를 해야 하는데 음소거 버튼은 간단한 toggle 버튼이라 리덕스툴을 이용할 필요까지 느끼지 못해서 컴포넌트로 분리한것있었습니다 :)

리팩토링을 하면서 어떤 것이 최선의 방법인지 고려해보겠습니다..!

2023-03-24 04:47 UTC, yourchaee commented on src/components/music/BackgroundMusicSetting.js
> +  }, [isMusicPlaying, sound]);
한 곳에서 기능을 한다는 말이 어떤 뜻일까요..? :)

2023-03-24 05:42 UTC, yourchaee commented on src/components/music/BackgroundMusicSetting.js
> +  }, [isMusicPlaying, sound]);
PR 업로드 전에 useEffect와 handler 기능이 합쳐져 있었는데, 그럴 경우 음악 재생이 겹치는 문제가 발생해 따로 분리해서 코드 작성했습니다 :)

2023-03-24 08:18 UTC, xollee approved these changes
음악 너무 좋습니다! 고생하셨습니다 👏

2023-03-24 08:56 UTC, j25nkh approved these changes

2023-03-24 09:55 UTC, merged